############################################################
#           FICHERO CONGIGURACIÓN EXPERIMENTOS 
#
# Guarda información relativa a: 
# - Nombre de ficheros
# - Directorio de escritura
############################################################

# --- Configuración de comparativa de las funciones de activación ---
[comparativas-funcion-activacion] 
DIRECTORIO_RESULTADOS = "Experimentos/comparativas-funciones-activacion/"
NOMBRE_FICHERO_TEST_WILCOXON = "test-Wilcoxon-(-10_10)_100000_15.txt"
NOMBRE_FICHERO_RESULTADOS_MEDIA = "resultado-comparativas-funciones-media-tiempos-(-10_10)_1000000_15.csv"
# Configuraciones relativas a parámetros del experimento
NUMERO_PARTICIONES = +15  # Veces que se tomarán medidas
LIMITE_INFERIOR = -10     # Cota inferior de los valores posibles
LIMITE_SUPERIOR = +10     # Cota superior de los valores posibles
FACTOR = +1000000         # Parámetro implicado con la cardinalidad del conjunto

# Configuración de 
[visualizacion-funciones-activacion]
# Descomentar: Para mostrar en la carpeta del experimento 
#DIRECTORIO_IMAGENES = "./Experimentos/comparativas-funciones-activacion/img/" #carpeta que contendrá las imágenes
# Descomentar: Para mostrar en la carpeta de la memoria
DIRECTORIO_IMAGENES = "./Memoria/img/funciones-activacion/" #carpeta que contendrá las imágenes

# Configuración de 
[visualizacion-inicializacion-pesos-R]
# Descomentar: Para mostrar en la carpeta del experimento 
DIRECTORIO_IMAGENES = "./Experimentos/inicializacion-pesos-red-neuronal/img/" #carpeta que contendrá las imágenes
# Descomentar: Para mostrar en la carpeta de la memoria
#DIRECTORIO_IMAGENES = "./Memoria/img/7-algoritmo-inicializar-pesos/"
