name: "check spelling"

on:
  push:
    tags:
      - '*'

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install tools
        run: .github/workflows/aspell-install.sh
      - name: Check spelling 
        run: ./spell-check.sh
