name: "check spelling"

on: push

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tools and spelling check
        run: make workflow-spell
